-- Auto-generated from schema-map-postgres.psd1 (map@mtime:2025-11-21T00:25:46Z)
-- engine: postgres
-- table:  event_inbox

CREATE TABLE IF NOT EXISTS event_inbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source VARCHAR(100) NOT NULL,
  event_key CHAR(36) NOT NULL,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  received_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  processed_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT uq_event_inbox_key UNIQUE (source, event_key),
  CONSTRAINT chk_event_inbox_status CHECK (status IN ('pending','processed','failed'))
);
